version: '3'

services:
  api:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    restart: always
    command: sh prestart.sh
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    hostname: ${DB_HOST}
    image: postgres:alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - ./docker_data/postgres:/var/lib/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
